version: '3.0'
services:
  web:
    image: ghcr.io/okp4/vtiger:7.4.0rc
    ports:
      - "8680:80"
    depends_on:
      - db
    env_file:
      - env
  db:
    image: mysql:5.7
    volumes:
      - ./db/config/my.cnf:/etc/mysql/my.cnf
    env_file:
      - env
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   ports:
  #     - "8583:80"
  #   depends_on:
  #     - db
