FROM alpine:3.14

LABEL \
  org.opencontainers.image.created=$IMAGE_CREATED \
  org.opencontainers.image.revision=$IMAGE_REVISION  \
  org.opencontainers.image.source=$IMAGE_SOURCE

ENTRYPOINT ["echo", "Hello World"]