version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    reviewers:
      - "okp4/maintainers"
    assignees:
      - "okp4/maintainers"
